"""The migration chain is the schema.

`alembic check` compares the models against the database the migrations built.
If they disagree, someone changed a model without generating a migration — the
exact failure that let `company.address` be JSONB in one place and TEXT in the
other until PostgreSQL rejected an insert.

Synchronous on purpose: alembic's async env.py calls `asyncio.run`, which
cannot be nested inside a running event loop.
"""

from __future__ import annotations

import os
import pathlib

import pytest

BACKEND = pathlib.Path(__file__).resolve().parent.parent

pytestmark = pytest.mark.skipif(
    not os.environ.get("POS_DATABASE_URL", "").startswith("postgresql"),
    reason="migrations are PostgreSQL-only; SQLite dev uses create_all()",
)


def _config():
    from alembic.config import Config

    cfg = Config(str(BACKEND / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND / "migrations"))
    return cfg


def test_models_match_the_migrated_database():
    """No pending schema change. Fails if a model moved without a migration."""
    from alembic import command
    from alembic.util.exc import AutogenerateDiffsDetected

    try:
        command.check(_config())
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "models and migrations disagree — run "
            "`alembic revision --autogenerate` and commit the result:\n" + str(exc)
        )


def test_migration_chain_is_linear():
    """One head. Two means a bad merge, and an ambiguous `upgrade head`."""
    from alembic.script import ScriptDirectory

    heads = ScriptDirectory.from_config(_config()).get_heads()
    assert len(heads) == 1, f"expected a single head, found {heads}"


def test_every_migration_can_be_undone():
    """A migration that cannot be reversed cannot be rolled back in production.

    Only checks that a downgrade body exists — the round trip itself is
    exercised by running `alembic downgrade base && alembic upgrade head`.
    """
    from alembic.script import ScriptDirectory

    script = ScriptDirectory.from_config(_config())
    missing = []
    for rev in script.walk_revisions():
        src = pathlib.Path(rev.path).read_text(encoding="utf-8")
        body = src.split("def downgrade()", 1)[-1]
        # A bare `pass` body means the migration is one-way.
        if body.strip().endswith("pass") and "op." not in body:
            missing.append(rev.revision)
    assert not missing, f"migrations with no downgrade: {missing}"
