/// The Dart ZATCA library must produce byte-identical output to the Python
/// reference in `zatca/`. These tests replay golden vectors generated by
/// `zatca/tools/gen_golden.py` and compare bytes — not shapes, not "looks
/// right". When sandbox validation lands on the Python side, it lands for the
/// tablet too, and if the two ever drift these fail loudly.
///
/// Regenerate after any change to the Python library:
///
///     python zatca/tools/gen_golden.py
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:pointycastle/ecc/api.dart';
import 'package:pos_app/zatca/hashing.dart';
import 'package:pos_app/zatca/invoice.dart';
import 'package:pos_app/zatca/qr.dart';
import 'package:pos_app/zatca/signing.dart';
import 'package:pos_app/zatca/tlv.dart';

Map<String, dynamic> _loadGolden() {
  final file = File('test/zatca/golden.json');
  if (!file.existsSync()) {
    fail('golden.json missing — run: python zatca/tools/gen_golden.py');
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

ZatcaLine _lineFromJson(Map<String, dynamic> json) => ZatcaLine(
      lineId: json['line_id'] as int,
      name: json['name'] as String,
      quantity: json['quantity'] as num,
      unitPrice: json['unit_price'] as int,
      lineNet: json['line_net'] as int,
      lineTax: json['line_tax'] as int,
      vatPercent: num.parse(json['vat_percent'] as String),
      unitCode: json['unit_code'] as String,
    );

ZatcaParty _sellerFromJson(Map<String, dynamic> json) {
  final address = json['address'] as Map<String, dynamic>;
  return ZatcaParty(
    name: json['name'] as String,
    vatNumber: json['vat_number'] as String,
    crNumber: (json['cr_number'] ?? '') as String,
    address: ZatcaAddress(
      street: address['street'] as String,
      building: address['building'] as String,
      city: address['city'] as String,
      postalCode: address['postal_code'] as String,
      district: address['district'] as String,
      country: address['country'] as String,
    ),
  );
}

void main() {
  final golden = _loadGolden();

  group('TLV', () {
    test('encodes byte-identically to the Python reference', () {
      for (final entry in (golden['tlv'] as List).cast<Map<String, dynamic>>()) {
        final binaryTags = (entry['binary_tags'] as List).cast<String>().toSet();
        final fields = <int, Object>{};
        (entry['fields'] as Map<String, dynamic>).forEach((tag, value) {
          fields[int.parse(tag)] = binaryTags.contains(tag)
              ? base64Decode(value as String)
              : value as String;
        });
        expect(encodeTlvBase64(fields), entry['b64'],
            reason: 'TLV mismatch for tags ${fields.keys.toList()}');
      }
    });

    test('an Arabic name is measured in bytes, not characters', () {
      // The failure this guards: 'مطعم فاطمة' is 10 characters and 19 bytes.
      // An implementation counting characters produces a QR that scans and
      // fails ZATCA validation.
      final encoded = encodeTlvField(ZatcaTag.sellerName, 'مطعم فاطمة');
      expect(encoded[1], 19);
      expect(encoded.length, 21);
    });

    test('rejects a value over the single-byte length limit', () {
      expect(() => encodeTlvField(1, 'x' * 256), throwsArgumentError);
    });

    test('round-trips through decode', () {
      final payload = encodeTlv({1: 'Bufia', 2: '310000000000003'});
      final decoded = decodeTlv(payload);
      expect(utf8.decode(decoded[1]!), 'Bufia');
      expect(utf8.decode(decoded[2]!), '310000000000003');
    });
  });

  group('money and timestamps', () {
    test('halalas format identically to the reference', () {
      for (final pair in (golden['money'] as List).cast<List>()) {
        expect(halalasToDecimalString(pair[0] as int), pair[1]);
      }
    });

    test('timestamps normalise to UTC exactly as the reference does', () {
      for (final pair in (golden['timestamps'] as List).cast<List>()) {
        expect(zatcaTimestamp(DateTime.parse(pair[0] as String)), pair[1]);
      }
    });

    test('a negative amount is refused rather than printed', () {
      expect(() => halalasToDecimalString(-1), throwsArgumentError);
    });
  });

  group('hash chain', () {
    test('the initial PIH matches the reference seed', () {
      expect(initialPih, golden['initial_pih']);
    });

    test('advancing carries the previous hash and increments once', () {
      const state = ChainState();
      expect(state.icv, 1);
      expect(state.pih, initialPih);
      final next = state.advance('somehash');
      expect(next.icv, 2);
      expect(next.pih, 'somehash');
    });
  });

  group('signing', () {
    final signing = golden['signing'] as Map<String, dynamic>;
    final publicDer = base64Decode(signing['public_der_b64'] as String);
    final payload = ascii.encode(signing['payload'] as String);

    test('verifies a signature made by the Python reference', () {
      // ECDSA uses a random nonce, so the two sides cannot produce the same
      // signature bytes. Cross-verification is the real proof they agree on
      // the curve, the digest and the DER encoding.
      expect(
        verifySignature(publicDer, signing['signature_b64'] as String, payload),
        isTrue,
      );
    });

    test('a Dart signature verifies against the reference public key', () {
      final made = signDigest(signing['private_pem'] as String, payload);
      expect(verifySignature(publicDer, made, payload), isTrue);
    });

    test('a tampered payload fails verification', () {
      expect(
        verifySignature(publicDer, signing['signature_b64'] as String,
            ascii.encode('not what was signed')),
        isFalse,
      );
    });

    test('loading the reference private key recovers its public point', () {
      final loaded = loadPrivateKey(signing['private_pem'] as String);
      final derived = ECPublicKey(zatcaCurve.G * loaded.d!, zatcaCurve);
      expect(encodePoint(derived), encodePoint(loadPublicKeyDer(publicDer)));
    });

    test('generated keys round-trip through PEM and DER', () {
      final pair = generateKeyPair();
      final signature = signDigest(pair.privatePem, payload);
      expect(verifySignature(pair.publicDer, signature, payload), isTrue);
    });

    test('the EGS serial is built in ZATCA order', () {
      expect(egsSerial('Bufia', 'TabPOS-10', 'abc-123'),
          '1-Bufia|2-TabPOS-10|3-abc-123');
      expect(() => egsSerial('Bu|fia', 'm', 'u'), throwsArgumentError);
    });
  });

  group('invoice XML', () {
    for (final entry
        in (golden['invoices'] as List).cast<Map<String, dynamic>>()) {
      final name = entry['name'] as String;
      final input = entry['input'] as Map<String, dynamic>;

      ZatcaInvoice build() => ZatcaInvoice(
            invoiceNumber: input['invoice_number'] as String,
            uuid: input['uuid'] as String,
            issuedAt: DateTime.parse(input['issued_at'] as String),
            seller: _sellerFromJson(input['seller'] as Map<String, dynamic>),
            lines: (input['lines'] as List)
                .cast<Map<String, dynamic>>()
                .map(_lineFromJson)
                .toList(),
            icv: input['icv'] as int,
            pih: input['pih'] as String,
            notes: (input['notes'] as List).cast<String>(),
          );

      test('$name canonicalises to the same bytes', () {
        final canonical = buildAndCanonicalize(build()).canonical;
        final expected = base64Decode(entry['canonical_b64'] as String);
        if (!_bytesEqual(canonical, expected)) {
          // Show where they diverge — a 4 KB byte-diff message is useless.
          final got = utf8.decode(canonical);
          final want = utf8.decode(expected);
          var i = 0;
          while (i < got.length && i < want.length && got[i] == want[i]) {
            i++;
          }
          final from = (i - 60).clamp(0, got.length);
          fail('canonical XML diverges at char $i\n'
              'expected: ...${want.substring(from, (i + 60).clamp(0, want.length))}\n'
              'actual:   ...${got.substring(from, (i + 60).clamp(0, got.length))}');
        }
      });

      test('$name hashes to the same digest', () {
        final canonical = buildAndCanonicalize(build()).canonical;
        expect(invoiceHash(canonical), entry['hash']);
      });
    }

    test('the VAT split holds the pinned parity values', () {
      // From real sales at the first customer: HUMMOS tier A 800 and
      // aggregator tier B 900.
      final tierA = ZatcaLine.fromInclusivePrice(
          lineId: 1, name: 'HUMMOS', quantity: 1, unitPriceInclusive: 800);
      expect((tierA.lineNet, tierA.lineTax), (696, 104));
      final tierB = ZatcaLine.fromInclusivePrice(
          lineId: 1, name: 'HUMMOS', quantity: 1, unitPriceInclusive: 900);
      expect((tierB.lineNet, tierB.lineTax), (783, 117));
    });

    test('net plus tax always reconciles to the gross the customer paid', () {
      for (var gross = 1; gross <= 2000; gross++) {
        final line = ZatcaLine.fromInclusivePrice(
            lineId: 1, name: 'x', quantity: 1, unitPriceInclusive: gross);
        expect(line.lineNet + line.lineTax, gross,
            reason: 'VAT split lost a halala at $gross');
      }
    });

    test('the document form carries a declaration and all namespaces', () {
      final xml = utf8.decode(buildInvoiceXml(ZatcaInvoice(
        invoiceNumber: 'T01-000001',
        uuid: '7a0e3f6e-1111-4222-8333-444455556666',
        issuedAt: DateTime.utc(2026, 8, 4, 6, 30),
        seller: _sellerFromJson(
            (golden['invoices'] as List).cast<Map<String, dynamic>>().first
                ['input']!['seller'] as Map<String, dynamic>),
        lines: [
          ZatcaLine.fromInclusivePrice(
              lineId: 1, name: 'HUMMOS', quantity: 1, unitPriceInclusive: 800),
        ],
        icv: 1,
        pih: initialPih,
      )));
      expect(xml, startsWith("<?xml version='1.0' encoding='UTF-8'?>"));
      expect(xml, contains('xmlns:ext='));
      // UBLExtensions survives in the document but never in what is hashed.
      expect(xml, contains('UBLExtensions'));
    });

    test('an invoice with no lines is refused', () {
      expect(
        () => buildInvoiceTree(ZatcaInvoice(
          invoiceNumber: 'T01-000001',
          uuid: 'u',
          issuedAt: DateTime.utc(2026),
          seller: _sellerFromJson(
              (golden['invoices'] as List).cast<Map<String, dynamic>>().first
                  ['input']!['seller'] as Map<String, dynamic>),
          lines: const [],
          icv: 1,
          pih: initialPih,
        )),
        throwsArgumentError,
      );
    });
  });

  group('QR', () {
    test('every tag except the signature matches the reference payload', () {
      final qr = golden['qr'] as Map<String, dynamic>;
      final input = qr['input'] as Map<String, dynamic>;
      final signing = golden['signing'] as Map<String, dynamic>;
      final publicDer = base64Decode(signing['public_der_b64'] as String);

      final built = buildQr(
        QrInput(
          sellerName: input['seller_name'] as String,
          vatNumber: input['vat_number'] as String,
          issuedAt: DateTime.parse(input['issued_at'] as String),
          totalWithVat: input['total_with_vat'] as int,
          vatTotal: input['vat_total'] as int,
          invoiceHash: input['invoice_hash'] as String,
          publicKeyDer: publicDer,
          csidSignature: input['csid_signature'] as String,
        ),
        signing['private_pem'] as String,
      );

      final mine = decodeTlvBase64(built);
      final reference = decodeTlvBase64(qr['qr_b64'] as String);

      for (final tag in reference.keys) {
        if (tag == ZatcaTag.signature) continue; // random nonce
        expect(mine[tag], isNotNull, reason: 'tag $tag missing');
        expect(_bytesEqual(mine[tag]!, reference[tag]!), isTrue,
            reason: 'tag $tag differs from the reference');
      }

      // The signature must verify against the hash it stamps — that is what
      // binds the QR to the document it was printed for.
      expect(
        verifySignature(publicDer, utf8.decode(mine[ZatcaTag.signature]!),
            ascii.encode(input['invoice_hash'] as String)),
        isTrue,
      );
    });

    test('the reference QR verifies with the reference key', () {
      final qr = golden['qr'] as Map<String, dynamic>;
      final input = qr['input'] as Map<String, dynamic>;
      final reference = decodeTlvBase64(qr['qr_b64'] as String);
      expect(
        verifySignature(
          Uint8List.fromList(reference[ZatcaTag.publicKey]!),
          utf8.decode(reference[ZatcaTag.signature]!),
          ascii.encode(input['invoice_hash'] as String),
        ),
        isTrue,
      );
    });

    test('a mismatched VAT number is refused before anything is signed', () {
      final signing = golden['signing'] as Map<String, dynamic>;
      expect(
        () => buildQr(
          QrInput(
            sellerName: 'x',
            vatNumber: '31000',
            issuedAt: DateTime.utc(2026),
            totalWithVat: 800,
            vatTotal: 104,
            invoiceHash: 'aGFzaA==',
            publicKeyDer: base64Decode(signing['public_der_b64'] as String),
            csidSignature: 'Y3NpZA==',
          ),
          signing['private_pem'] as String,
        ),
        throwsArgumentError,
      );
    });

    test('inspect decodes a payload for support', () {
      final fields = inspectQr((golden['qr'] as Map<String, dynamic>)['qr_b64']
          as String);
      expect(fields['vat_number'], '310000000000003');
      expect(fields['public_key'], startsWith('<'));
    });
  });
}

bool _bytesEqual(List<int> a, List<int> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
