"""floor plan, table sessions and reservations

Revision ID: 009ad17b35e3
Revises: 5650ee789d9a
Create Date: 2026-08-04 14:12:19.496934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009ad17b35e3'
down_revision: Union[str, Sequence[str], None] = '5650ee789d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_section',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'code')
    )
    op.create_index(op.f('ix_floor_section_branch_id'), 'floor_section', ['branch_id'], unique=False)
    op.create_index(op.f('ix_floor_section_server_version'), 'floor_section', ['server_version'], unique=False)
    op.create_index(op.f('ix_floor_section_tenant_id'), 'floor_section', ['tenant_id'], unique=False)
    op.create_table('dining_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('seats', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('min_seats', sa.Integer(), nullable=True),
    sa.Column('max_seats', sa.Integer(), nullable=True),
    sa.Column('pos_x', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pos_y', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('width', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('height', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('shape', sa.String(length=12), server_default=sa.text("'square'"), nullable=False),
    sa.Column('can_reserve', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['floor_section.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'table_no')
    )
    op.create_index(op.f('ix_dining_table_branch_id'), 'dining_table', ['branch_id'], unique=False)
    op.create_index(op.f('ix_dining_table_server_version'), 'dining_table', ['server_version'], unique=False)
    op.create_index('ix_dining_table_sync', 'dining_table', ['tenant_id', 'branch_id', 'server_version'], unique=False)
    op.create_index(op.f('ix_dining_table_tenant_id'), 'dining_table', ['tenant_id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=True),
    sa.Column('guest_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('reserved_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default=sa.text('90'), nullable=False),
    sa.Column('occasion', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'booked'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['dining_table.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_branch_id'), 'reservation', ['branch_id'], unique=False)
    op.create_index(op.f('ix_reservation_tenant_id'), 'reservation', ['tenant_id'], unique=False)
    op.create_index('ix_reservation_when', 'reservation', ['tenant_id', 'branch_id', 'reserved_for'], unique=False)
    op.create_table('table_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.String(length=64), nullable=True),
    sa.Column('staff_id', sa.Uuid(), nullable=True),
    sa.Column('guests', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
    sa.Column('sale_uuid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['dining_table.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_session_branch_id'), 'table_session', ['branch_id'], unique=False)
    op.create_index('ix_table_session_open', 'table_session', ['tenant_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_table_session_table_id'), 'table_session', ['table_id'], unique=False)
    op.create_index(op.f('ix_table_session_tenant_id'), 'table_session', ['tenant_id'], unique=False)
    op.create_index('ux_table_session_one_open', 'table_session', ['table_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('table_session_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('prodnum', sa.Integer(), nullable=False),
    sa.Column('line_des', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.Column('seat_no', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sent_to_kitchen', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voided', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['table_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_line_session', 'table_session_line', ['session_id', 'line_no'], unique=False)
    op.create_index(op.f('ix_table_session_line_session_id'), 'table_session_line', ['session_id'], unique=False)
    op.create_index(op.f('ix_table_session_line_tenant_id'), 'table_session_line', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_session_line_tenant_id'), table_name='table_session_line')
    op.drop_index(op.f('ix_table_session_line_session_id'), table_name='table_session_line')
    op.drop_index('ix_session_line_session', table_name='table_session_line')
    op.drop_table('table_session_line')
    op.drop_index('ux_table_session_one_open', table_name='table_session', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_table_session_tenant_id'), table_name='table_session')
    op.drop_index(op.f('ix_table_session_table_id'), table_name='table_session')
    op.drop_index('ix_table_session_open', table_name='table_session')
    op.drop_index(op.f('ix_table_session_branch_id'), table_name='table_session')
    op.drop_table('table_session')
    op.drop_index('ix_reservation_when', table_name='reservation')
    op.drop_index(op.f('ix_reservation_tenant_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_branch_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_dining_table_tenant_id'), table_name='dining_table')
    op.drop_index('ix_dining_table_sync', table_name='dining_table')
    op.drop_index(op.f('ix_dining_table_server_version'), table_name='dining_table')
    op.drop_index(op.f('ix_dining_table_branch_id'), table_name='dining_table')
    op.drop_table('dining_table')
    op.drop_index(op.f('ix_floor_section_tenant_id'), table_name='floor_section')
    op.drop_index(op.f('ix_floor_section_server_version'), table_name='floor_section')
    op.drop_index(op.f('ix_floor_section_branch_id'), table_name='floor_section')
    op.drop_table('floor_section')
    # ### end Alembic commands ###
