"""kds stations tickets and device roles

Revision ID: 3f8d6119d693
Revises: 2edb2a2885b8
Create Date: 2026-08-04 14:50:16.963437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8d6119d693'
down_revision: Union[str, Sequence[str], None] = '2edb2a2885b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_station',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('station_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'station_no')
    )
    op.create_index(op.f('ix_kitchen_station_branch_id'), 'kitchen_station', ['branch_id'], unique=False)
    op.create_index(op.f('ix_kitchen_station_server_version'), 'kitchen_station', ['server_version'], unique=False)
    op.create_index('ix_kitchen_station_sync', 'kitchen_station', ['tenant_id', 'branch_id', 'server_version'], unique=False)
    op.create_index(op.f('ix_kitchen_station_tenant_id'), 'kitchen_station', ['tenant_id'], unique=False)
    op.create_table('kitchen_ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.Column('sale_type_no', sa.Integer(), nullable=True),
    sa.Column('sale_type_name', sa.Text(), nullable=True),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('sale_uuid', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('device_uuid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bumped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_ticket_branch_id'), 'kitchen_ticket', ['branch_id'], unique=False)
    op.create_index('ix_kitchen_ticket_rail', 'kitchen_ticket', ['tenant_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_kitchen_ticket_tenant_id'), 'kitchen_ticket', ['tenant_id'], unique=False)
    op.create_table('kitchen_ticket_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('prodnum', sa.Integer(), nullable=False),
    sa.Column('line_des', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('seat_no', sa.Integer(), nullable=True),
    sa.Column('station_no', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('voided', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['kitchen_ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_ticket_line_tenant_id'), 'kitchen_ticket_line', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_kitchen_ticket_line_ticket_id'), 'kitchen_ticket_line', ['ticket_id'], unique=False)
    op.create_index('ix_kticket_line', 'kitchen_ticket_line', ['ticket_id', 'line_no'], unique=False)
    op.add_column('device', sa.Column('role', sa.String(length=8), server_default=sa.text("'pos'"), nullable=False))
    op.add_column('device', sa.Column('kds_station_no', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('print_loc', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'print_loc')
    op.drop_column('device', 'kds_station_no')
    op.drop_column('device', 'role')
    op.drop_index('ix_kticket_line', table_name='kitchen_ticket_line')
    op.drop_index(op.f('ix_kitchen_ticket_line_ticket_id'), table_name='kitchen_ticket_line')
    op.drop_index(op.f('ix_kitchen_ticket_line_tenant_id'), table_name='kitchen_ticket_line')
    op.drop_table('kitchen_ticket_line')
    op.drop_index(op.f('ix_kitchen_ticket_tenant_id'), table_name='kitchen_ticket')
    op.drop_index('ix_kitchen_ticket_rail', table_name='kitchen_ticket')
    op.drop_index(op.f('ix_kitchen_ticket_branch_id'), table_name='kitchen_ticket')
    op.drop_table('kitchen_ticket')
    op.drop_index(op.f('ix_kitchen_station_tenant_id'), table_name='kitchen_station')
    op.drop_index('ix_kitchen_station_sync', table_name='kitchen_station')
    op.drop_index(op.f('ix_kitchen_station_server_version'), table_name='kitchen_station')
    op.drop_index(op.f('ix_kitchen_station_branch_id'), table_name='kitchen_station')
    op.drop_table('kitchen_station')
    # ### end Alembic commands ###
