"""product button appearance

Revision ID: 4c9ced948f95
Revises: 86f4d1f40b31
Create Date: 2026-08-10 15:44:17.971847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9ced948f95'
down_revision: Union[str, Sequence[str], None] = '86f4d1f40b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('button_text', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('fore_color', sa.String(length=7), nullable=True))
    op.add_column('product', sa.Column('back_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'back_color')
    op.drop_column('product', 'fore_color')
    op.drop_column('product', 'button_text')
    # ### end Alembic commands ###
