"""menus and menu pages

Revision ID: 82b4ae6b00eb
Revises: 4c9ced948f95
Create Date: 2026-08-10 16:20:14.689437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b4ae6b00eb'
down_revision: Union[str, Sequence[str], None] = '4c9ced948f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


NEW_TENANT_TABLES = ["menu", "menu_page"]


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('menu',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('menu_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('revenue_centre', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'menu_no')
    )
    op.create_index(op.f('ix_menu_server_version'), 'menu', ['server_version'], unique=False)
    op.create_index('ix_menu_sync', 'menu', ['tenant_id', 'server_version'], unique=False)
    op.create_index(op.f('ix_menu_tenant_id'), 'menu', ['tenant_id'], unique=False)
    op.create_table('menu_page',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('menu_no', sa.Integer(), nullable=False),
    sa.Column('screen_no', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=True),
    sa.Column('pos_y', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'menu_no', 'screen_no')
    )
    op.create_index(op.f('ix_menu_page_server_version'), 'menu_page', ['server_version'], unique=False)
    op.create_index('ix_menu_page_sync', 'menu_page', ['tenant_id', 'server_version'], unique=False)
    op.create_index(op.f('ix_menu_page_tenant_id'), 'menu_page', ['tenant_id'], unique=False)
    op.add_column('menu_screen', sa.Column('fore_color', sa.String(length=7), nullable=True))
    op.add_column('menu_screen', sa.Column('back_color', sa.String(length=7), nullable=True))

    # Autogenerate cannot see RLS. A tenant table without a policy has no
    # isolation, so it is added by hand exactly as every other one has been.
    if _is_postgres():
        for table in NEW_TENANT_TABLES:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(
                f"""
                CREATE POLICY tenant_isolation ON {table}
                USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
                """
            )
            op.execute(f"GRANT SELECT, INSERT, UPDATE ON {table} TO pos_app")


def downgrade() -> None:
    if _is_postgres():
        for table in NEW_TENANT_TABLES:
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_screen', 'back_color')
    op.drop_column('menu_screen', 'fore_color')
    op.drop_index(op.f('ix_menu_page_tenant_id'), table_name='menu_page')
    op.drop_index('ix_menu_page_sync', table_name='menu_page')
    op.drop_index(op.f('ix_menu_page_server_version'), table_name='menu_page')
    op.drop_table('menu_page')
    op.drop_index(op.f('ix_menu_tenant_id'), table_name='menu')
    op.drop_index('ix_menu_sync', table_name='menu')
    op.drop_index(op.f('ix_menu_server_version'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
