"""initial schema from models

Revision ID: a040bf2b32c6
Revises: 
Create Date: 2026-08-04 12:48:03.980884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a040bf2b32c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), server_default=sa.text("'standalone'"), nullable=False),
    sa.Column('erp_base_url', sa.Text(), nullable=True),
    sa.Column('erp_credentials', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('vat_number', sa.String(length=15), nullable=False),
    sa.Column('cr_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'vat_number')
    )
    op.create_index(op.f('ix_company_tenant_id'), 'company', ['tenant_id'], unique=False)
    op.create_table('licence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grace_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licence_tenant_id'), 'licence', ['tenant_id'], unique=False)
    op.create_table('branch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('address', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'Asia/Riyadh'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_branch_company_id'), 'branch', ['company_id'], unique=False)
    op.create_index(op.f('ix_branch_tenant_id'), 'branch', ['tenant_id'], unique=False)
    op.create_table('pay_method',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('methodnum', sa.Integer(), nullable=False),
    sa.Column('descript', sa.Text(), nullable=False),
    sa.Column('descript_ar', sa.Text(), nullable=True),
    sa.Column('is_cash', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('opens_drawer', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'methodnum')
    )
    op.create_index(op.f('ix_pay_method_server_version'), 'pay_method', ['server_version'], unique=False)
    op.create_index(op.f('ix_pay_method_tenant_id'), 'pay_method', ['tenant_id'], unique=False)
    op.create_table('tax_rate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_inclusive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rate_server_version'), 'tax_rate', ['server_version'], unique=False)
    op.create_index(op.f('ix_tax_rate_tenant_id'), 'tax_rate', ['tenant_id'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('device_uuid', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('receipt_prefix', sa.String(length=8), nullable=False),
    sa.Column('is_hub', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('egs_serial', sa.Text(), nullable=True),
    sa.Column('csid', sa.Text(), nullable=True),
    sa.Column('csid_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('csid_status', sa.String(length=16), server_default=sa.text("'none'"), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_icv', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_uuid')
    )
    op.create_index(op.f('ix_device_branch_id'), 'device', ['branch_id'], unique=False)
    op.create_index(op.f('ix_device_tenant_id'), 'device', ['tenant_id'], unique=False)
    op.create_table('menu_screen',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('buttons_across', sa.Integer(), nullable=True),
    sa.Column('buttons_down', sa.Integer(), nullable=True),
    sa.Column('is_modifier_screen', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'menu_id')
    )
    op.create_index(op.f('ix_menu_screen_server_version'), 'menu_screen', ['server_version'], unique=False)
    op.create_index(op.f('ix_menu_screen_tenant_id'), 'menu_screen', ['tenant_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('prodnum', sa.Integer(), nullable=False),
    sa.Column('descript', sa.Text(), nullable=False),
    sa.Column('descript_ar', sa.Text(), nullable=True),
    sa.Column('print_des', sa.Text(), nullable=True),
    sa.Column('price_a', sa.BigInteger(), nullable=False),
    sa.Column('price_b', sa.BigInteger(), nullable=True),
    sa.Column('price_c', sa.BigInteger(), nullable=True),
    sa.Column('prodtype', sa.Integer(), nullable=True),
    sa.Column('tax_applies', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_weighed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('manual_price', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_modifier', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ref_code', sa.String(length=32), nullable=True),
    sa.Column('unit_des', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'prodnum')
    )
    op.create_index(op.f('ix_product_server_version'), 'product', ['server_version'], unique=False)
    op.create_index('ix_product_sync', 'product', ['tenant_id', 'branch_id', 'server_version'], unique=False)
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('empnum', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('must_set_pin', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sec_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ref_code', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'empnum')
    )
    op.create_index(op.f('ix_staff_server_version'), 'staff', ['server_version'], unique=False)
    op.create_index(op.f('ix_staff_tenant_id'), 'staff', ['tenant_id'], unique=False)
    op.create_table('menu_button',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('menu_screen_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('prodnum', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=True),
    sa.Column('pos_y', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('fore_color', sa.Integer(), nullable=True),
    sa.Column('back_color', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['menu_screen_id'], ['menu_screen.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_button_server_version'), 'menu_button', ['server_version'], unique=False)
    op.create_index(op.f('ix_menu_button_tenant_id'), 'menu_button', ['tenant_id'], unique=False)
    op.create_table('sale',
    sa.Column('sale_uuid', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_no', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('num_guests', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('sale_type', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('net_total', sa.BigInteger(), nullable=False),
    sa.Column('tax_total', sa.BigInteger(), nullable=False),
    sa.Column('final_total', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'closed'"), nullable=False),
    sa.Column('zatca_uuid', sa.Uuid(), nullable=True),
    sa.Column('zatca_icv', sa.BigInteger(), nullable=True),
    sa.Column('zatca_pih', sa.Text(), nullable=True),
    sa.Column('zatca_hash', sa.Text(), nullable=True),
    sa.Column('zatca_qr', sa.Text(), nullable=True),
    sa.Column('zatca_xml', sa.Text(), nullable=True),
    sa.Column('zatca_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('zatca_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zatca_error', sa.Text(), nullable=True),
    sa.Column('erp_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('erp_ref', sa.Text(), nullable=True),
    sa.Column('erp_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('sale_uuid'),
    sa.UniqueConstraint('device_id', 'zatca_icv', name='ux_sale_device_icv'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'receipt_no')
    )
    op.create_index('ix_sale_erp_todo', 'sale', ['erp_status'], unique=False, postgresql_where=sa.text("erp_status = 'pending'"))
    op.create_index('ix_sale_tenant_date', 'sale', ['tenant_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_sale_tenant_id'), 'sale', ['tenant_id'], unique=False)
    op.create_index('ix_sale_zatca_todo', 'sale', ['zatca_status'], unique=False, postgresql_where=sa.text("zatca_status = 'pending'"))
    op.create_table('sale_line',
    sa.Column('line_uuid', sa.Uuid(), nullable=False),
    sa.Column('sale_uuid', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('prodnum', sa.Integer(), nullable=False),
    sa.Column('line_des', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.Column('discount', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('net_amount', sa.BigInteger(), nullable=False),
    sa.Column('tax_amount', sa.BigInteger(), nullable=False),
    sa.Column('line_total', sa.BigInteger(), nullable=False),
    sa.Column('seat_no', sa.Integer(), nullable=True),
    sa.Column('voided', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['sale_uuid'], ['sale.sale_uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('line_uuid')
    )
    op.create_index(op.f('ix_sale_line_sale_uuid'), 'sale_line', ['sale_uuid'], unique=False)
    op.create_index(op.f('ix_sale_line_tenant_id'), 'sale_line', ['tenant_id'], unique=False)
    op.create_table('sale_payment',
    sa.Column('payment_uuid', sa.Uuid(), nullable=False),
    sa.Column('sale_uuid', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('methodnum', sa.Integer(), nullable=False),
    sa.Column('tender', sa.BigInteger(), nullable=False),
    sa.Column('change_given', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('auth_code', sa.String(length=64), nullable=True),
    sa.Column('card_type', sa.String(length=32), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voided', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['sale_uuid'], ['sale.sale_uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('payment_uuid')
    )
    op.create_index(op.f('ix_sale_payment_sale_uuid'), 'sale_payment', ['sale_uuid'], unique=False)
    op.create_index(op.f('ix_sale_payment_tenant_id'), 'sale_payment', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_payment_tenant_id'), table_name='sale_payment')
    op.drop_index(op.f('ix_sale_payment_sale_uuid'), table_name='sale_payment')
    op.drop_table('sale_payment')
    op.drop_index(op.f('ix_sale_line_tenant_id'), table_name='sale_line')
    op.drop_index(op.f('ix_sale_line_sale_uuid'), table_name='sale_line')
    op.drop_table('sale_line')
    op.drop_index('ix_sale_zatca_todo', table_name='sale', postgresql_where=sa.text("zatca_status = 'pending'"))
    op.drop_index(op.f('ix_sale_tenant_id'), table_name='sale')
    op.drop_index('ix_sale_tenant_date', table_name='sale')
    op.drop_index('ix_sale_erp_todo', table_name='sale', postgresql_where=sa.text("erp_status = 'pending'"))
    op.drop_table('sale')
    op.drop_index(op.f('ix_menu_button_tenant_id'), table_name='menu_button')
    op.drop_index(op.f('ix_menu_button_server_version'), table_name='menu_button')
    op.drop_table('menu_button')
    op.drop_index(op.f('ix_staff_tenant_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_server_version'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_index('ix_product_sync', table_name='product')
    op.drop_index(op.f('ix_product_server_version'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_menu_screen_tenant_id'), table_name='menu_screen')
    op.drop_index(op.f('ix_menu_screen_server_version'), table_name='menu_screen')
    op.drop_table('menu_screen')
    op.drop_index(op.f('ix_device_tenant_id'), table_name='device')
    op.drop_index(op.f('ix_device_branch_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_tax_rate_tenant_id'), table_name='tax_rate')
    op.drop_index(op.f('ix_tax_rate_server_version'), table_name='tax_rate')
    op.drop_table('tax_rate')
    op.drop_index(op.f('ix_pay_method_tenant_id'), table_name='pay_method')
    op.drop_index(op.f('ix_pay_method_server_version'), table_name='pay_method')
    op.drop_table('pay_method')
    op.drop_index(op.f('ix_branch_tenant_id'), table_name='branch')
    op.drop_index(op.f('ix_branch_company_id'), table_name='branch')
    op.drop_table('branch')
    op.drop_index(op.f('ix_licence_tenant_id'), table_name='licence')
    op.drop_table('licence')
    op.drop_index(op.f('ix_company_tenant_id'), table_name='company')
    op.drop_table('company')
    op.drop_table('tenant')
    # ### end Alembic commands ###
