"""sale types, price tiers, order numbers

Revision ID: c3b21e9fb7c8
Revises: d2d030b64387
Create Date: 2026-08-04 14:30:58.509015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b21e9fb7c8'
down_revision: Union[str, Sequence[str], None] = 'd2d030b64387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('sale_type_no', sa.Integer(), nullable=False),
    sa.Column('descript', sa.Text(), nullable=False),
    sa.Column('descript_ar', sa.Text(), nullable=True),
    sa.Column('price_tier', sa.String(length=1), server_default=sa.text("'a'"), nullable=False),
    sa.Column('is_aggregator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_external_ref', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('needs_table', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_methodnum', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'sale_type_no')
    )
    op.create_index(op.f('ix_sales_type_server_version'), 'sales_type', ['server_version'], unique=False)
    op.create_index('ix_sales_type_sync', 'sales_type', ['tenant_id', 'server_version'], unique=False)
    op.create_index(op.f('ix_sales_type_tenant_id'), 'sales_type', ['tenant_id'], unique=False)
    op.create_table('order_number_counter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('next_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'business_date')
    )
    op.create_index(op.f('ix_order_number_counter_branch_id'), 'order_number_counter', ['branch_id'], unique=False)
    op.create_index(op.f('ix_order_number_counter_tenant_id'), 'order_number_counter', ['tenant_id'], unique=False)
    op.add_column('product', sa.Column('price_d', sa.BigInteger(), nullable=True))
    op.add_column('product', sa.Column('price_e', sa.BigInteger(), nullable=True))
    op.add_column('product', sa.Column('price_f', sa.BigInteger(), nullable=True))
    op.add_column('product', sa.Column('price_g', sa.BigInteger(), nullable=True))
    op.add_column('product', sa.Column('price_h', sa.BigInteger(), nullable=True))
    op.add_column('product', sa.Column('price_i', sa.BigInteger(), nullable=True))
    op.add_column('product', sa.Column('price_j', sa.BigInteger(), nullable=True))
    op.add_column('sale', sa.Column('order_no', sa.Integer(), nullable=True))
    op.add_column('sale', sa.Column('external_ref', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'external_ref')
    op.drop_column('sale', 'order_no')
    op.drop_column('product', 'price_j')
    op.drop_column('product', 'price_i')
    op.drop_column('product', 'price_h')
    op.drop_column('product', 'price_g')
    op.drop_column('product', 'price_f')
    op.drop_column('product', 'price_e')
    op.drop_column('product', 'price_d')
    op.drop_index(op.f('ix_order_number_counter_tenant_id'), table_name='order_number_counter')
    op.drop_index(op.f('ix_order_number_counter_branch_id'), table_name='order_number_counter')
    op.drop_table('order_number_counter')
    op.drop_index(op.f('ix_sales_type_tenant_id'), table_name='sales_type')
    op.drop_index('ix_sales_type_sync', table_name='sales_type')
    op.drop_index(op.f('ix_sales_type_server_version'), table_name='sales_type')
    op.drop_table('sales_type')
    # ### end Alembic commands ###
